### ISSUE TITLE
Close items add themselves to observer's inventory

### ISSUE THREAD

**Issue by Time6628** [codeHusky/HuskyUI-Plugin#15]
When you click the close item from a Page state, it will add the barrier to the player's inventory. It also does this with other close items if the inventory is large enough.

![image](http://i.imgur.com/qlZMacm.gif "Image")

Here's the code https://github.com/Time6628/Market/blob/d207f5da56fb4e0b441aa14d2d11488702b46acd/src/main/java/com/kookykraftmc/market/datastores/RedisDataStore.java#L215-L246.

**Comment by codeHusky** [comment]
Version info
HuskyUI info
Sponge info

**Comment by Time6628** [comment]
I was using a very old version of SpongeVanilla, sorry. It's fixed now.
