### ISSUE TITLE
Phase error in latest sponge

### ISSUE THREAD

**Issue by clienthax** [codeHusky/HuskyUI-Plugin#20]
https://pastebin.ubuntu.com/p/CQb5GJ4D2j/

**Comment by codeHusky** [comment]
oh fun.

**Comment by codeHusky** [comment]
seems like a sponge bug tbh, i don't know why I wouldn't be able to close an inventory during an inventory event.

**Comment by clienthax** [comment]
@codeHusky If you figure what exactly is causing it just raise it on the sponge tracker :)

**Comment by codeHusky** [comment]
Seems to be no longer an issue. I'm closing this unless you have been able to reproduce it @clienthax
