### ISSUE TITLE
Call inventory.close() in a task

### ISSUE THREAD

**Issue by BrainStone** [codeHusky/HuskyUI-Plugin#24]
Following the discussions here: SpongePowered/SpongeCommon#1865 and here: SpongePowered/SpongeCommon#1869, the call to `inventory.close()` should happen the next tick, meaning it should be called in a sync schelduled oneshot task.

**Comment by BrainStone** [comment]
Nevermind, pre2 contains the fix.

**Comment by codeHusky** [comment]
Ree
