### ISSUE TITLE
CommandAction

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyUI-Plugin#7]
Something to run commands with options for running as server or as player.

**Comment by Redrield** [comment]
Is it worth making something for this or should we just stop adding new stuff and wait for @FerusGrim to finish his rewrite

**Comment by codeHusky** [comment]
Waiting for the rewrite would be wise

**Comment by FerusGrim** [comment]
Feel free to add things, @codeHusky @Redrield.

Worst comes to worse, I port it to the re-write.
