### ISSUE TITLE
PageBuilder#addElement improperly places Elements

### ISSUE THREAD

**Issue by FerusGrim** [codeHusky/HuskyUI-Plugin#8]
```java
        public PageBuilder addElement(@Nonnull final Element element) {
            this.elements.put(this.elements.size(), element);
            return this;
        }
```

Considering that the key to this Map is an Integer, it's entirely possible that `this.elements.size()` doesn't always represent the correct placement.

We will have to find a solution to this.

Example:

```java
public void test(final PageBuilder builder) {
    builder.putElement(2, someElement);
    builder.putElement(6, someOtherElement);
    builder.addElement(evenAnotherElement);
}
```

By the time `PageBuilder#addElement` is called, `Map#size()` will return `2`. Meaning `PageBuilder#addElement` will actually overwrite the first value.

**Comment by codeHusky** [comment]
Care to explain how it could not always be placed properly?

**Comment by FerusGrim** [comment]
Example:

```java
public void test(final PageBuilder builder) {
    builder.putElement(2, someElement);
    builder.putElement(6, someOtherElement);
    builder.addElement(evenAnotherElement);
}
```

By the time `PageBuilder#addElement` is called, `Map#size()` will return `2`. Meaning `PageBuilder#addElement` will actually overwrite the first value.

**Comment by codeHusky** [comment]
Well, here's a fix.
We have an `ArrayList<Element>` as well, which we add elements to added in any way.
When building, if we're in auto mode, we reset `elements` and then put, by index, all of the `Elements` in the secondary list.

**Comment by FerusGrim** [comment]
I think it would be wiser to just insert them into the `Map` in a more rational matter.

When `PageBuilder#putElement` is called, we also save where, in the index, it was added. Then, when `PageBuilder#addElement` is called, we increase that index by one and add the Element in that position. If it conflicts with an Element already in that position, we push it back until we find an open slot.

This would best represent the intentions of most developers, so far as I can think of.

**Comment by codeHusky** [comment]
That would be the best and most flexible way to do it. My main concern is people putting items *way* out of bounds.

**Comment by FerusGrim** [comment]
I'm not going to bother covering the API with bubble wrap.

If they want to assign an item that exceeds the bounds and crashes the game so hard their server ends up in Asgard, that's their own choice.

**Comment by codeHusky** [comment]
I could argue that people using Auto Pages shouldn't be `putElement`ing at all, and if they want to do something fancier they could just extend Page, but that's my input.

**Comment by FerusGrim** [comment]
Eh. Most people wouldn't. But unless we want to create an entirely separate object/builder for something that, in the end, is a pretty minute difference, I think we just have to leave it.

**Comment by codeHusky** [comment]
alright, i'll wait for your fix.
