### ISSUE TITLE
RunnableAction#runAction doesn't make a super call

### ISSUE THREAD

**Issue by FerusGrim** [codeHusky/HuskyUI-Plugin#9]
This is the current `RunnableAction#runAction` method.

```java
    @Override
    public void runAction(@Nonnull final String currentState) {
        if (this.runnable != null) {
            this.runnable.run(this);
        } else {
            this.getObserver().sendMessage(Text.of(TextColors.RED, "Cannot run a null action!"));
        }
    }
```

This is, technically, fine. Because you should be able to define your own actions without necessarily moving your position in the GUI.

However, rather than making people forcefully call this every time that _isn't_ the case, I suggest an alternative:

Rework Actions entirely.

Have fun.

jk, I'll probably make a PR on it soon. <3

**Comment by codeHusky** [comment]
I remember seeing this suggested somewhere else. I think even PR'd but i guess that vanished? confuse.

**Comment by codeHusky** [comment]
![image](https://user-images.githubusercontent.com/6946558/27759767-76b00354-5dfe-11e7-891c-6b9d101812b5.png)
yeah it existed, and then it didn't
Make sure its conditionally enabled or you're gonna get a slap on the wrist

**Comment by FerusGrim** [comment]
When I'm done with Actions, the two probably won't even be related. So no worries, there.

**Comment by codeHusky** [comment]
Yay.
